using System;
using System.Collections.Generic;

namespace CryBarEditor.Classes;

public enum FieldInputMode { Free, Suggest, Number }

public record SimpleFieldDefinition(string Tag, string Label, FieldInputMode Mode);

public static class ProtoConstants
{
    // ── Simple Field Definitions ──────────────────────────────────────────────
    public static readonly SimpleFieldDefinition[] SimpleFields =
    [
        // Identity
        new("displaynameid",       "Display Name",       FieldInputMode.Free),
        new("editornameid",        "Editor Name",        FieldInputMode.Free),
        new("rollovertextid",      "Rollover Text",      FieldInputMode.Free),
        new("shortrollovertextid", "Short Rollover Text",FieldInputMode.Free),
        // Visuals
        new("icon",                "Icon Path",             FieldInputMode.Suggest),
        new("animfile",            "Animation File",        FieldInputMode.Suggest),
        new("soundsetfile",        "Sound Set File",        FieldInputMode.Suggest),
        // Physics
        new("obstructionradiusx",  "Obstruction Radius X",  FieldInputMode.Number),
        new("obstructionradiusz",  "Obstruction Radius Z",  FieldInputMode.Number),
        new("turnrate",            "Turn Rate",             FieldInputMode.Number),
        new("maxvelocity",         "Max Velocity",          FieldInputMode.Number),
        new("maxrunvelocity",      "Max Run Velocity",      FieldInputMode.Number),
        // Combat / Stats
        new("initialhitpoints",    "Initial Hit Points",    FieldInputMode.Number),
        new("maxhitpoints",        "Max Hit Points",        FieldInputMode.Number),
        new("trainpoints",         "Train Points",          FieldInputMode.Number),
        new("weightclass",         "Weight Class",          FieldInputMode.Number),
        new("populationcount",     "Population Count",      FieldInputMode.Number),
        new("buildlimit",          "Build Limit",           FieldInputMode.Number),
        new("los",                 "Line of Sight",         FieldInputMode.Number),
        // Type / Behavior
        new("impacttype",          "Impact Type",           FieldInputMode.Suggest),
        new("unitaitype",          "Unit AI Type",          FieldInputMode.Suggest),
        new("movementtype",        "Movement Type",         FieldInputMode.Suggest),
        // Tactics
        new("tactics",             "Tactics",               FieldInputMode.Suggest),
    ];

    public static readonly string[] KnownResourceTypes = ["Food", "Wood", "Gold", "Favor"];
    public static readonly string[] KnownArmorTypes    = ["Hack", "Pierce", "Crush"];
    public static readonly string[] KnownDamageTypes   = ["Hack", "Pierce", "Crush", "Divine"];

    // ── ProtoAction type mappings ─────────────────────────────────────────────
    // ── Known Unit Types ──────────────────────────────────────────────────────
    public static readonly string[] KnownUnitTypes =
    [
        "AbstractArcher", "AbstractArcherShip", "AbstractArmory", "AbstractAsura",
        "AbstractCavalry", "AbstractCloseCombatShip", "AbstractDock", "AbstractDwarf",
        "AbstractEmpowerer", "AbstractFarm", "AbstractFishingShip", "AbstractFlyingUnit",
        "AbstractFortress", "AbstractGullinbursti", "AbstractHealer", "AbstractHouseBuildLimit",
        "AbstractInfantry", "AbstractInvisibleWall", "AbstractKuafu", "AbstractMachineWorkshop",
        "AbstractMarket", "AbstractMidasGold", "AbstractMilitaryCamp", "AbstractMonument",
        "AbstractNezha", "AbstractOracle", "AbstractPharaoh", "AbstractSamurai",
        "AbstractScout", "AbstractSettlement", "AbstractShrineJapanese", "AbstractSiegeShip",
        "AbstractSiegeWeapon", "AbstractSocketedTownCenter", "AbstractTemple", "AbstractTitan",
        "AbstractTower", "AbstractTowerBuildLimit", "AbstractTownCenter", "AbstractTransportShip",
        "AbstractVillager", "AbstractWalkingWoods", "AbstractWall", "AbstractWarship",
        "AbstractWarshipHero", "AbstractWonder", "AffectedByTownBell", "AnimalOfSet",
        "AnimalPredator", "AnimalPrey", "AnimalReactive", "ArcherLineUpgraded",
        "BuildLimitSharedAtlantean", "BuildLimitSharedGreek", "BuildLimitSharedNorse",
        "Building", "BuildingClass", "CavalryLineUpgraded", "CountsTowardEconomicScore",
        "CountsTowardMilitaryScore", "DisplayQueue", "Dropsite", "EconomicUnit",
        "EconomicUpgraded", "EmbellishmentClass", "EmplacementBuilding", "FavorDropsite",
        "FishResource", "FoodDropsite", "FoodResource", "GoldDropsite", "GoldResource",
        "Herdable", "HerdableMagnet", "Hero", "HeroInfantry", "HeroShadowUpgraded",
        "HumanSoldier", "Huntable", "HuntedResource", "InfantryLineUpgraded",
        "LogicalTypeAffectedByBuildingChainAutoBuild", "LogicalTypeAffectedByCeaseFireBuildingSlow",
        "LogicalTypeAffectedByRestoration", "LogicalTypeAffectedBySunRay",
        "LogicalTypeAffectedByValleyOfTheKings", "LogicalTypeAffectedByValor",
        "LogicalTypeAgeUpBuilding", "LogicalTypeAgressiveNatureUnit",
        "LogicalTypeAnimalLarge", "LogicalTypeAnimalSmall", "LogicalTypeArchaicMythUnit",
        "LogicalTypeAutoAttackFocusBuildings", "LogicalTypeBuildingEmpoweredForLOS",
        "LogicalTypeBuildingLarge", "LogicalTypeBuildingNotWonderOrTitan",
        "LogicalTypeBuildingSmall", "LogicalTypeBuildingThatCanBeEmpowered",
        "LogicalTypeBuildingThatConvertsConvertibles", "LogicalTypeBuildingsNotWalls",
        "LogicalTypeBuildingsThatShoot", "LogicalTypeCapturableBuilding",
        "LogicalTypeClassicalMythUnit", "LogicalTypeConvertsHerds", "LogicalTypeDamageShading",
        "LogicalTypeDivineImmunity", "LogicalTypeEarthquakeAttack", "LogicalTypeEasySelectAvoid",
        "LogicalTypeFindArchery", "LogicalTypeFindBarracks", "LogicalTypeFindFoodDropsite",
        "LogicalTypeFindGoldDropsite", "LogicalTypeFindMilitaryHero", "LogicalTypeFindStable",
        "LogicalTypeFindWoodDropsite", "LogicalTypeFreezableMythUnit", "LogicalTypeGarrisonInShips",
        "LogicalTypeGatherNoDropsite", "LogicalTypeHandUnitsAttack", "LogicalTypeHandUnitsAutoAttack",
        "LogicalTypeHealableHero", "LogicalTypeHealed", "LogicalTypeHeroicMythUnit",
        "LogicalTypeLandMilitary", "LogicalTypeMilitaryProductionBuilding",
        "LogicalTypeMinimapFilterEconomic", "LogicalTypeMinimapFilterMilitary",
        "LogicalTypeMythUnitNotFlying", "LogicalTypeMythUnitNotTitan",
        "LogicalTypeMythUnitThatGeneratesFavor", "LogicalTypeMythicMythUnit",
        "LogicalTypeNavalMilitary", "LogicalTypeNavalMythUnit", "LogicalTypeNeededForVictory",
        "LogicalTypeNorseSoldierThatBuilds", "LogicalTypeNotEconomicOrMilitaryUnit",
        "LogicalTypeParticipatesInBattlecries", "LogicalTypePickable",
        "LogicalTypePredatorsAttack", "LogicalTypeRangedMythUnit", "LogicalTypeRangedUnitsAttack",
        "LogicalTypeRangedUnitsAutoAttack", "LogicalTypeSeidrTarget",
        "LogicalTypeSharedHeroSelection", "LogicalTypeShipNotHero", "LogicalTypeSunRayProjectile",
        "LogicalTypeTCBuildLimit", "LogicalTypeTartarianGateValidOverlapPlacement",
        "LogicalTypeTeleporterBuilding", "LogicalTypeTrainableMythUnit",
        "LogicalTypeUnitIsConstructed", "LogicalTypeValidBoltTarget", "LogicalTypeValidEidolon",
        "LogicalTypeValidForestProtectionPlacement", "LogicalTypeValidFrostTarget",
        "LogicalTypeValidLocustSwarmTarget", "LogicalTypeValidMeteorTarget",
        "LogicalTypeValidSPCUnitsDeadCondition", "LogicalTypeValidSentinelTarget",
        "LogicalTypeValidShiftingSandsTarget", "LogicalTypeValidShockwaveTarget",
        "LogicalTypeValidSiphonTarget", "LogicalTypeValidSpyTarget",
        "LogicalTypeValidTornadoAttack", "LogicalTypeValidTraitorTarget",
        "LogicalTypeValidUnderworldInvasionTarget", "LogicalTypeVillagerNotHero",
        "LogicalTypeVillagersAttack", "LogicalTypeVillagersAttackResponse",
        "LogicalTypeVillagersRespondToAttack", "LogicalTypeWitherable",
        "MajorHero", "MilitaryBuilding", "MilitaryUnit", "MinorHero", "MythUnit",
        "MythUnitCavalry", "MythUnitMelee", "MythUnitRanged", "MythUnitSiege",
        "Nature", "NatureClass", "NavalUnit", "NonConvertableHerdable", "Projectile",
        "Ranged", "Resource", "RespawnTrainTarget", "Ship", "SiegeLineUpgraded",
        "Socket", "TradeUnit", "TradeableFrom", "TradeableTo", "Transport", "Tree",
        "Unattackable", "Unit", "UnitClass", "ValidIdleVillager", "VillagerHero",
        "WildCrops", "WoodDropsite", "WoodResource",
    ];

    // ── Known Flags ───────────────────────────────────────────────────────────
    public static readonly string[] KnownFlags =
    [
        "AbilitiesOnBothPages", "AdjustPositionOnTerrainCollision", "AllowAutoGarrison",
        "AllowPlacementOnIce", "AlwaysAllowOverPopCap", "AlwaysFullColorAsCursor",
        "AlwaysShowAbilities", "AmphibiousBirth", "AnnounceConversion", "AnnounceDestruction",
        "AnnounceFoundationStarted", "AreaDamageConstant", "AutoAbilityStartDisabled",
        "AutoCommandSingleUnit", "AutoCommandStartDisabled", "AutoTrainable",
        "AuxAutoAbilityStartDisabled", "BallisticTrackSource", "BattleMusicTrigger",
        "BuildingCanDoWorkOnUnitIfCharged", "BuildingShowTactics", "CanAutoHeal",
        "CanAutoTransform", "CanTargetButTakesNoDamage", "CannotAttackDisabledUnits",
        "CannotAttackIfNature", "CannotSnare", "CastAbilitySelf", "CheckCreepOnPlacement",
        "CollidesWithProjectiles", "ColorTransformNonNature", "CommonCommands",
        "ConstrainOrientation", "ConvertOnStartBuild", "ConvertToNatureAtZeroHitpoints",
        "ConvertToTOB", "CopyNearbyTree", "CorpseDecays", "CreateUnitGroupAutomatically",
        "DecalStickToWaterSurface", "DeleteConfirmation", "DependentAttach", "DependentAttack",
        "DependentKeepAlive", "DestroyProjectile", "DestroyUnderBuilding", "DieAtZeroResources",
        "DirectProjectile", "DisplayBuildingProgress", "DisplayMinimumRange", "DisplayRange",
        "DisplayRangeOverride", "DisplayUpgradeProgress", "DoNotAllowAlliedGarrison",
        "DoNotDieAtZeroHitpoints", "DoNotDragSelectWithUnits", "DoNotShowOnMiniMap",
        "DoNotValidateResourceInventory", "DoNotYawDuringMovement", "DontMarkExtraFog",
        "DontRotateObstruction", "DoppleOnlyWhenDead", "Doppled", "DynamicUpdate",
        "DynamicUpdateAnimate", "ExcludeFromIdleQuery", "ExcludeFromMoveAllMilitary",
        "ExperienceUnit", "FadeOutDecalOnDeath", "FadeOutDuringDeathAnimation",
        "FakeAsTreeIfEnemy", "FlareOnFullyBuilt", "FlattenGround", "FlyingUnit",
        "ForceBuildingData", "ForceCountAsGatherer", "ForceDeletable", "ForceEmpowerable",
        "ForceNormalDeathAnim", "ForceSecondPage", "ForceSquareSelection", "ForceToNature",
        "GivesLOSToAll", "GodPowerExclusion", "GroupSelection", "HasContinuousParticles",
        "HasDefaultAttack", "HasGatherPoint", "HeroNamePharaoh", "HeroNameSimple",
        "HideCostFromDetailHelp", "HideFromDialogs", "HideGarrisonCapacity", "HideGarrisonFlag",
        "HideHPBarFromOpponents", "HideHitpointsIfNature", "HideMinimapIndicatorFromOpponents",
        "HideResourceInventory", "HideStances", "HitSpawnIgnorePlacement",
        "IgnoreCarryCapacityWhenDead", "IgnoreDependentEditor", "IgnoreForFavoriteUnitCount",
        "IgnoreGridPlacement", "IgnoreIfCharmed", "Immoveable", "InitialGarrisonOnly",
        "Invulnerable", "InvulnerableIfNature", "InvulnerableOnBirth", "KeepGarrisonTimeshift",
        "KillOnAnimLoop", "KillsTargetAfterPickupAction", "KnockoutDeath", "LifespanBirth",
        "LikeBonusPreview", "MagnetDoesNotLockUnits", "MilitaryCommands", "MinimapDisplayOnTop",
        "NeverCountDeathAsLoss", "NoHPBar", "NoIdleActions", "NoLockedAnimationOnDeath",
        "NoNotificationEventOnFullyBuilt", "NoRandomVariation", "NoTieToGround", "NoUnitAI",
        "NonAutoFormedUnit", "NonCollideable", "NonSolid", "NotAlive", "NotAttackableByNature",
        "NotCommandable", "NotDeathTracked", "NotDeleteable", "NotDeleteableFoundation",
        "NotEjectable", "NotKBTracked", "NotManuallyPlaceable", "NotObscuredByUnitsAsFoundation",
        "NotObscuredByUnitsForOpponents", "NotPlayerPlaceable", "NotPreferredMilitaryCommandingUnit",
        "NotPushable", "NotRepairable", "NotSearchable", "NotSelectable",
        "ObscuredByUnits", "ObscuresUnits", "OnlyInEditor", "OrientUnitWithGround",
        "OrientUnitWithGroundRoll", "PaintTextureWhenPlacing", "Pickable", "PlaceAnywhere",
        "PlaceAsFoundation", "PlaceSocketWhenPlacing", "PlaySoundOnConversion",
        "PlayerOwnsObstruction", "PrayableTo", "PreventRespawn", "PreventsWallBuilding",
        "Projectile", "ProjectileTerrainOnly", "PushPlacement", "RMCanRotate",
        "RangeIndicatorForAbilityCasting", "RecoverableDeathHeal", "Relic",
        "RequireExactRateMatch", "RevealFoundation", "RevertToSocketAtZeroHitpoints",
        "RotateInPlace", "SelectWithObstruction", "SharedGarrison", "ShowGarrisonButton",
        "ShowUntouchedFoundation", "SkipFlyingDeathAnim", "SnapPlacement", "SolidFoundation",
        "SpawnWhenHitGround", "SplitQueue", "StartOnAnimationUpdate", "StartOnNoUpdate",
        "TieToWaterSurface", "TileAlignPlacement", "TrainVisualUpdate", "UnitTransformBuildLimit",
        "UnitTransformFree", "UnlimitedSupply", "UpgradeSocket",
        "UseAlignedObstructionOnMinimap", "UseAltConvertCursor", "UseAltEmpowerCursor",
        "UseAltRepairCursor", "UseChargeAfterTransform", "UseChargeIfNotIdle",
        "UseChargeOnDamaged", "UseFarmingAnims", "UseSharedBuildLimit", "UseStaticFarmingAnims",
        "VariationLocked", "VisibleOwnerOnly", "VisibleUnderFog", "VisibleUnderFogIfNature",
        "VisibleUnderFogOnlyAfterSeen", "Wanders", "WitherDoesDamage", "wallBuild",
    ];

    // ── Field suggestions (merged with BAR data at runtime) ───────────────────
    public static Dictionary<string, List<string>> FieldSuggestions { get; } = new()
    {
        ["impacttype"]   = ["Armoured", "Metal", "Stone", "Titan", "Tree", "Unarmoured", "Wood"],
        ["unitaitype"]   = ["Civilian", "HandCombative", "NavalHandCombative", "Passive", "Prey", "RangedCombative"],
        ["movementtype"] = ["air", "amphibious", "land", "titan", "water"],
        ["tactics"] = [
            "animal_herdable.tactics", "animal_predator.tactics", "animal_prey.tactics",
            "animal_reactive.tactics", "area_damage.tactics", "area_heal.tactics",
            "area_invisibility.tactics", "area_slow.tactics", "arkantos_uber.tactics",
            "auto_convert.tactics", "autogather.tactics", "axe_cart.tactics",
            "bai_hu.tactics", "battle_boar.tactics", "bellerophon.tactics",
            "blazing_prairie_strike.tactics", "brokk.tactics", "caladria.tactics",
            "carnivora.tactics", "cavalry_speed_charge.tactics", "chainattack_beam.tactics",
            "charged_modify.tactics", "charged_modify_vfx.tactics", "chi_you.tactics",
            "chicken_of_set.tactics", "chukonu.tactics", "communal_hearth.tactics",
            "container.tactics", "delayed_transform.tactics", "dock.tactics", "eitri.tactics",
            "eyes_revealer.tactics", "fafnir.tactics", "farm_shennong.tactics", "fei.tactics",
            "fei_trail.tactics", "fenrir.tactics", "fenris_wolf_brood.tactics",
            "fishing_ship.tactics", "forest_fire.tactics", "fortress.tactics",
            "giant_gate_ram.tactics", "gold_mine.tactics", "greek_hero.tactics",
            "guardian.tactics", "hamadryad.tactics", "hamadryad_ambush.tactics",
            "hamadryad_tree.tactics", "HandAttack.tactics", "handattack.tactics",
            "handattack_antiwall.tactics", "handattack_aoeattack.tactics",
            "handattack_autoboost.tactics", "handattack_buckattack.tactics",
            "handattack_channelattack.tactics", "handattack_chargedhandattack.tactics",
            "handattack_chargedrangedattack.tactics", "handattack_dash.tactics",
            "handattack_eat.tactics", "handattack_freezeattack.tactics",
            "handattack_gore.tactics", "handattack_heal.tactics",
            "handattack_idle_stat_bonus.tactics", "handattack_jumpattack.tactics",
            "handattack_selfdestruct.tactics", "handattack_shockwave.tactics",
            "handattack_teleport.tactics", "handattack_throw.tactics",
            "handattack_titanattack.tactics", "harpy.tactics", "heal.tactics",
            "hesperides_tree.tactics", "honengyo.tactics", "howling_celestial_dog.tactics",
            "huang_zhao_wu.tactics", "hun_dun.tactics", "idle_speed_bonus.tactics",
            "jiang_ziya.tactics", "jormun_elver.tactics", "jorogumo.tactics",
            "kappa.tactics", "kappa_swampland.tactics", "kastor.tactics",
            "king_folstag.tactics", "kitsune.tactics", "kraken.tactics", "kuafu.tactics",
            "lampades.tactics", "li_jing.tactics", "locust_swarm.tactics",
            "lykaon_wolf.tactics", "maelstrom.tactics", "manor.tactics", "miko.tactics",
            "monument.tactics", "mountain_giant.tactics", "move.tactics", "mummy.tactics",
            "myth_self_destruct.tactics", "nereid.tactics", "nezha.tactics", "nidhogg.tactics",
            "onmoraki.tactics", "oracle.tactics", "orpheus.tactics", "ox_cart.tactics",
            "peach_blossom.tactics", "pentekonter.tactics", "perseus.tactics",
            "pharaoh.tactics", "phoenix.tactics", "phoenix_egg.tactics", "pioneer.tactics",
            "polyphemus.tactics", "priest.tactics", "priest_spc.tactics",
            "progressive_damage.tactics", "qilin.tactics", "qing_long.tactics",
            "qiongqi.tactics", "qiongqi_air.tactics", "rangedattack.tactics",
            "rangedattack_antiwall.tactics", "rangedattack_chargedrangedattack.tactics",
            "rangedattack_chargedrangedattack_noflying.tactics",
            "rangedattack_freezeattack.tactics", "rangedattack_heal.tactics",
            "rangedattack_lightningattack.tactics", "rangedattack_rangedattackflying.tactics",
            "reginleif.tactics", "resource_los.tactics", "rock_giant.tactics", "sage.tactics",
            "sentry_tower.tactics", "serpent.tactics", "setna.tactics", "shade_spc.tactics",
            "shinigami.tactics", "shinobi.tactics", "shrine_japanese.tactics",
            "siege_bireme.tactics", "siege_tower.tactics", "siren.tactics",
            "son_of_osiris.tactics", "statue_of_lightning.tactics", "sun_ray_revealer.tactics",
            "tanuki.tactics", "taotie.tactics", "temple.tactics", "titan.tactics",
            "titan_chiyou.tactics", "titan_prometheus.tactics", "torii_gate.tactics",
            "tornado.tactics", "town_center.tactics", "trade.tactics", "trading_post.tactics",
            "troll.tactics", "vfx_heal.tactics", "villager.tactics", "villager_norse.tactics",
            "wasen.tactics", "water_carnivora.tactics", "wen_zhong.tactics",
            "white_horse_cavalry.tactics", "xuan_wu.tactics", "yang_jian.tactics",
            "yasuko.tactics", "yazi.tactics", "ying_long.tactics", "yuki_onna.tactics",
            "zhuque.tactics",
        ],
        ["icon"] = [
            @"resources\atlantean\player_color\units\arcus_hero_icon.png",
            @"resources\atlantean\player_color\units\arcus_icon.png",
            @"resources\atlantean\player_color\units\argus_icon.png",
            @"resources\atlantean\player_color\units\automaton_icon.png",
            @"resources\atlantean\player_color\units\behemoth_icon.png",
            @"resources\atlantean\player_color\units\bireme_icon.png",
            @"resources\atlantean\player_color\units\caladria_icon.png",
            @"resources\atlantean\player_color\units\caravan_atlantean_icon.png",
            @"resources\atlantean\player_color\units\carnivora_icon.png",
            @"resources\atlantean\player_color\units\centimanus_icon.png",
            @"resources\atlantean\player_color\units\cheiroballista_hero_icon.png",
            @"resources\atlantean\player_color\units\cheiroballista_icon.png",
            @"resources\atlantean\player_color\units\contarius_hero_icon.png",
            @"resources\atlantean\player_color\units\contarius_icon.png",
            @"resources\atlantean\player_color\units\destroyer_hero_icon.png",
            @"resources\atlantean\player_color\units\destroyer_icon.png",
            @"resources\atlantean\player_color\units\dryad_icon.png",
            @"resources\atlantean\player_color\units\fanatic_hero_icon.png",
            @"resources\atlantean\player_color\units\fanatic_icon.png",
            @"resources\atlantean\player_color\units\fire_ship_icon.png",
            @"resources\atlantean\player_color\units\fire_siphon_icon.png",
            @"resources\atlantean\player_color\units\fishing_ship_atlantean_icon.png",
            @"resources\atlantean\player_color\units\katapeltes_hero_icon.png",
            @"resources\atlantean\player_color\units\katapeltes_icon.png",
            @"resources\atlantean\player_color\units\lampades_icon.png",
            @"resources\atlantean\player_color\units\man_o_war_icon.png",
            @"resources\atlantean\player_color\units\murmillo_hero_icon.png",
            @"resources\atlantean\player_color\units\murmillo_icon.png",
            @"resources\atlantean\player_color\units\nereid_icon.png",
            @"resources\atlantean\player_color\units\oracle_hero_icon.png",
            @"resources\atlantean\player_color\units\oracle_icon.png",
            @"resources\atlantean\player_color\units\promethean_icon.png",
            @"resources\atlantean\player_color\units\promethean_offspring_icon.png",
            @"resources\atlantean\player_color\units\satyr_icon.png",
            @"resources\atlantean\player_color\units\servant_icon.png",
            @"resources\atlantean\player_color\units\siege_bireme_icon.png",
            @"resources\atlantean\player_color\units\spider_egg_icon.png",
            @"resources\atlantean\player_color\units\stymphalian_bird_icon.png",
            @"resources\atlantean\player_color\units\tartarian_spawn_icon.png",
            @"resources\atlantean\player_color\units\titan_atlantean_icon.png",
            @"resources\atlantean\player_color\units\transport_ship_atlantean_icon.png",
            @"resources\atlantean\player_color\units\turma_hero_icon.png",
            @"resources\atlantean\player_color\units\turma_icon.png",
            @"resources\atlantean\player_color\units\villager_atlantean_hero_icon.png",
            @"resources\atlantean\player_color\units\villager_atlantean_icon.png",
            @"resources\atlantean\player_color\units\water_carnivora_icon.png",
            @"resources\atlantean\static_color\buildings\citadel_center_atlantean_icon.png",
            @"resources\atlantean\static_color\buildings\counter_barracks_icon.png",
            @"resources\atlantean\static_color\buildings\economic_guild_icon.png",
            @"resources\atlantean\static_color\buildings\hesperides_tree_icon.png",
            @"resources\atlantean\static_color\buildings\manor_icon.png",
            @"resources\atlantean\static_color\buildings\military_barracks_icon.png",
            @"resources\atlantean\static_color\buildings\mirror_tower_icon.png",
            @"resources\atlantean\static_color\buildings\palace_icon.png",
            @"resources\atlantean\static_color\buildings\sky_passage_icon.png",
            @"resources\atlantean\static_color\buildings\tartarian_gate_icon.png",
            @"resources\atlantean\static_color\buildings\town_center_atlantean_icon.png",
            @"resources\atlantean\static_color\buildings\village_center_atlantean_icon.png",
            @"resources\chinese\player_color\units\axe_cart_icon.png",
            @"resources\chinese\player_color\units\baihu_icon.png",
            @"resources\chinese\player_color\units\caravan_chinese_icon.png",
            @"resources\chinese\player_color\units\dao_swordsman_icon.png",
            @"resources\chinese\player_color\units\ge_halberdier_icon.png",
            @"resources\chinese\player_color\units\qilin_icon.png",
            @"resources\chinese\player_color\units\samurai_icon.png",
            @"resources\chinese\player_color\units\titan_chinese_icon.png",
            @"resources\chinese\player_color\units\villager_chinese_icon.png",
            @"resources\chinese\static_color\buildings\citadel_center_chinese_icon.png",
            @"resources\chinese\static_color\buildings\town_center_chinese_icon.png",
            @"resources\egyptian\player_color\units\anubite_icon.png",
            @"resources\egyptian\player_color\units\axeman_icon.png",
            @"resources\egyptian\player_color\units\catapult_icon.png",
            @"resources\egyptian\player_color\units\pharaoh_icon.png",
            @"resources\egyptian\player_color\units\sphinx_icon.png",
            @"resources\egyptian\player_color\units\titan_egyptian_icon.png",
            @"resources\egyptian\player_color\units\villager_egyptian_icon.png",
            @"resources\egyptian\static_color\buildings\barracks_icon.png",
            @"resources\egyptian\static_color\buildings\citadel_center_egyptian_icon.png",
            @"resources\egyptian\static_color\buildings\town_center_egyptian_icon.png",
            @"resources\greek\player_color\units\achilles_icon.png",
            @"resources\greek\player_color\units\ajax_icon.png",
            @"resources\greek\player_color\units\centaur_icon.png",
            @"resources\greek\player_color\units\chimera_icon.png",
            @"resources\greek\player_color\units\cyclops_icon.png",
            @"resources\greek\player_color\units\hoplite_icon.png",
            @"resources\greek\player_color\units\hydra_icon.png",
            @"resources\greek\player_color\units\minotaur_icon.png",
            @"resources\greek\player_color\units\titan_greek_icon.png",
            @"resources\greek\player_color\units\villager_greek_icon.png",
            @"resources\greek\static_color\buildings\citadel_center_greek_icon.png",
            @"resources\greek\static_color\buildings\fortress_icon.png",
            @"resources\greek\static_color\buildings\town_center_greek_icon.png",
            @"resources\japanese\player_color\units\asura_icon.png",
            @"resources\japanese\player_color\units\bushi_icon.png",
            @"resources\japanese\player_color\units\daimyo_icon.png",
            @"resources\japanese\player_color\units\oni_icon.png",
            @"resources\japanese\player_color\units\samurai_icon.png",
            @"resources\japanese\player_color\units\shogun_icon.png",
            @"resources\japanese\player_color\units\tengu_icon.png",
            @"resources\japanese\player_color\units\titan_japanese_icon.png",
            @"resources\japanese\player_color\units\villager_japanese_icon.png",
            @"resources\japanese\static_color\buildings\castle_icon.png",
            @"resources\japanese\static_color\buildings\citadel_center_japanese_icon.png",
            @"resources\japanese\static_color\buildings\town_center_japanese_icon.png",
            @"resources\nature\animals\flying\harpy_icon.png",
            @"resources\nature\animals\flying\hawk_icon.png",
            @"resources\nature\animals\land\bear_icon.png",
            @"resources\nature\animals\land\boar_icon.png",
            @"resources\nature\animals\land\deer_icon.png",
            @"resources\nature\animals\land\lion_icon.png",
            @"resources\nature\animals\land\wolf_icon.png",
            @"resources\nature\animals\naval\fish_icon.png",
            @"resources\norse\player_color\units\berserk_icon.png",
            @"resources\norse\player_color\units\huskarl_icon.png",
            @"resources\norse\player_color\units\jarl_icon.png",
            @"resources\norse\player_color\units\titan_norse_icon.png",
            @"resources\norse\player_color\units\valkyrie_icon.png",
            @"resources\norse\player_color\units\villager_dwarf_icon.png",
            @"resources\norse\player_color\units\villager_norse_icon.png",
            @"resources\norse\static_color\buildings\citadel_center_norse_icon.png",
            @"resources\norse\static_color\buildings\great_hall_icon.png",
            @"resources\norse\static_color\buildings\town_center_norse_icon.png",
            @"resources\shared\static_color\buildings\armory_icon.png",
            @"resources\shared\static_color\buildings\dock_icon.png",
            @"resources\shared\static_color\buildings\farm_icon.png",
            @"resources\shared\static_color\buildings\house_icon.png",
            @"resources\shared\static_color\buildings\market_icon.png",
            @"resources\shared\static_color\buildings\temple_icon.png",
            @"resources\shared\static_color\buildings\titan_gate_icon.png",
            @"resources\shared\static_color\buildings\wonder_icon.png",
        ],
        ["animfile"] = [
            @"atlantean\units\archery\arcus\arcus.xml",
            @"atlantean\units\cavalry\contarius\contarius.xml",
            @"atlantean\units\economic\villager_atlantean\villager_atlantean.xml",
            @"atlantean\units\infantry\destroyer\destroyer.xml",
            @"atlantean\units\myth\automaton\automaton.xml",
            @"atlantean\units\myth\titan\titan_atlantean.xml",
            @"chinese\units\archery\chu_ko_nu\chu_ko_nu.xml",
            @"chinese\units\cavalry\tiger_cavalry\tiger_cavalry.xml",
            @"chinese\units\economic\villager_chinese\villager_chinese.xml",
            @"chinese\units\myth\tao_tie\tao_tie.xml",
            @"chinese\units\myth\titan\titan_xing_tian.xml",
            @"egyptian\units\archery\chariot_archer\chariot_archer.xml",
            @"egyptian\units\cavalry\camel_rider\camel_rider.xml",
            @"egyptian\units\economic\villager_egyptian\villager_egyptian.xml",
            @"egyptian\units\myth\anubite\anubite.xml",
            @"egyptian\units\myth\sphinx\sphinx.xml",
            @"egyptian\units\myth\titan\titan_bird.xml",
            @"greek\units\archery\toxotes\toxotes.xml",
            @"greek\units\cavalry\hetairos\hetairos.xml",
            @"greek\units\economic\villager_greek\villager_greek.xml",
            @"greek\units\infantry\hoplite\hoplite.xml",
            @"greek\units\myth\centaur\centaur.xml",
            @"greek\units\myth\chimera\chimera.xml",
            @"greek\units\myth\cyclops\cyclops.xml",
            @"greek\units\myth\hydra\hydra.xml",
            @"greek\units\myth\minotaur\minotaur.xml",
            @"greek\units\myth\titan\titan_cerberus.xml",
            @"japanese\units\economic\villager_japanese\villager_japanese.xml",
            @"japanese\units\infantry\samurai\samurai.xml",
            @"japanese\units\myth\asura\asura.xml",
            @"japanese\units\myth\oni\oni.xml",
            @"japanese\units\myth\tengu\tengu.xml",
            @"japanese\units\myth\titan\titan_yamata_no_orochi.xml",
            @"norse\units\cavalry\jarl\jarl.xml",
            @"norse\units\economic\villager_norse\villager_norse.xml",
            @"norse\units\infantry\berserk\berserk.xml",
            @"norse\units\infantry\huskarl\huskarl.xml",
            @"norse\units\myth\frost_giant\frost_giant.xml",
            @"norse\units\myth\nidhogg\nidhogg.xml",
            @"norse\units\myth\valkyrie\valkyrie.xml",
            @"norse\units\myth\titan\titan_ymir.xml",
            @"nature\animals\land\bear\bear.xml",
            @"nature\animals\land\boar\boar.xml",
            @"nature\animals\land\deer\deer.xml",
            @"nature\animals\land\lion\lion.xml",
            @"nature\animals\land\wolf\wolf.xml",
            @"shared\buildings\farm\farm.xml",
            @"shared\buildings\settlement\settlement.xml",
        ],
        ["soundsetfile"] = [
            @"atlantean\vo\arcus\arcus.xml",
            @"atlantean\vo\automaton\automaton.xml",
            @"atlantean\vo\behemoth\behemoth.xml",
            @"atlantean\vo\centimanus\centimanus.xml",
            @"atlantean\vo\destroyer\destroyer.xml",
            @"atlantean\vo\villager_atlantean\villager_atlantean.xml",
            @"chinese\vo\chu_ko_nu\chu_ko_nu.xml",
            @"chinese\vo\tiger_cavalry\tiger_cavalry.xml",
            @"chinese\vo\tao_tie\tao_tie.xml",
            @"chinese\vo\villager_chinese\villager_chinese.xml",
            @"egyptian\vo\anubite\anubite.xml",
            @"egyptian\vo\chariot_archer\chariot_archer.xml",
            @"egyptian\vo\pharaoh\pharaoh.xml",
            @"egyptian\vo\sphinx\sphinx.xml",
            @"egyptian\vo\villager_egyptian\villager_egyptian.xml",
            @"greek\vo\achilles\achilles.xml",
            @"greek\vo\centaur\centaur.xml",
            @"greek\vo\chimera\chimera.xml",
            @"greek\vo\cyclops\cyclops.xml",
            @"greek\vo\hoplite\hoplite.xml",
            @"greek\vo\hydra\hydra.xml",
            @"greek\vo\minotaur\minotaur.xml",
            @"greek\vo\villager_greek\villager_greek.xml",
            @"japanese\vo\asura\asura.xml",
            @"japanese\vo\bushi\bushi.xml",
            @"japanese\vo\daimyo\daimyo.xml",
            @"japanese\vo\oni\oni.xml",
            @"japanese\vo\samurai\samurai.xml",
            @"japanese\vo\tengu\tengu.xml",
            @"japanese\vo\villager_japanese\villager_japanese.xml",
            @"norse\vo\berserk\berserk.xml",
            @"norse\vo\huskarl\huskarl.xml",
            @"norse\vo\jarl\jarl.xml",
            @"norse\vo\nidhogg\nidhogg.xml",
            @"norse\vo\valkyrie\valkyrie.xml",
            @"norse\vo\villager_norse\villager_norse.xml",
            @"shared\sfx\buildings\armory.xml",
            @"shared\sfx\buildings\citadel_center.xml",
            @"shared\sfx\buildings\dock.xml",
            @"shared\sfx\buildings\farm.xml",
            @"shared\sfx\buildings\house.xml",
            @"shared\sfx\buildings\market.xml",
            @"shared\sfx\buildings\temple.xml",
            @"shared\sfx\buildings\titan_gate.xml",
            @"shared\sfx\buildings\town_center.xml",
            @"shared\sfx\buildings\wonder.xml",
            @"nature\animals\bear\bear.xml",
            @"nature\animals\boar\boar.xml",
            @"nature\animals\deer\deer.xml",
            @"nature\animals\lion\lion.xml",
            @"nature\animals\wolf\wolf.xml",
        ],
    };

    /// <summary>Merge lists extracted from BAR proto.xml into FieldSuggestions.</summary>
    public static void MergeBarData(
        IEnumerable<string> icons,
        IEnumerable<string> animFiles,
        IEnumerable<string> soundSets,
        IEnumerable<string> impactTypes,
        IEnumerable<string> unitAiTypes,
        IEnumerable<string> movementTypes,
        IEnumerable<string> tactics)
    {
        MergeInto("icon",         icons);
        MergeInto("animfile",     animFiles);
        MergeInto("soundsetfile", soundSets);
        MergeInto("impacttype",   impactTypes);
        MergeInto("unitaitype",   unitAiTypes);
        MergeInto("movementtype", movementTypes);
        MergeInto("tactics",      tactics);
    }

    static void MergeInto(string key, IEnumerable<string> values)
    {
        if (!FieldSuggestions.TryGetValue(key, out var list))
        {
            list = [];
            FieldSuggestions[key] = list;
        }
        var set = new HashSet<string>(list, StringComparer.OrdinalIgnoreCase);
        foreach (var v in values)
            if (set.Add(v)) list.Add(v);
        list.Sort(StringComparer.OrdinalIgnoreCase);
    }
}
