using System.Linq;
using System.Text.Json;
using CryBar;
using CryBar.TMM;

namespace CryBar.Export;

/// <summary>
/// Metadata stamped into a GLB's <c>extras.crybar</c> object so re-importers can
/// recover non-mesh fields (main_matrix, attachments' fields, DDT params, ...) without
/// needing the source TMM/TMA/DDT files. Schema is defined in the GLB-to-TMM spec.
/// </summary>
public sealed class GlbExtras
{
    public TmmSection Tmm { get; init; } = new();
    public Dictionary<string, TmaSection> Tma { get; init; } = new();
    public List<DdtEntry> Ddt { get; init; } = new();

    public sealed class TmmSection
    {
        public float[] ExtendedBbox { get; set; } = new float[6];
        public float[] MainMatrix { get; set; } = IdentityMatrix4x4();
        public string[] Submodels { get; set; } = ["default"];
        public byte AutoBurnMode { get; set; }
        public bool Raytracing { get; set; }
        public bool TerrainEmb { get; set; }
        public ModifiedBoneEntry[] ModifiedBones { get; set; } = [];
        // Per-bone collision data (offset XYZ + radius) parallel to the bone array.
        // Length is either 0 (no data) or 4 * numBones with 4-stride [X, Y, Z, Radius].
        public float[] BoneCollisions { get; set; } = [];
        public AutoAttachInfo? AutoAttach { get; set; }
        public float[][] ImpactPoints { get; set; } = [];
        public AttachmentEntry[] Attachments { get; set; } = [];
        public List<string> LossySections { get; set; } = new();

        static float[] IdentityMatrix4x4() =>
            [1, 0, 0, 0,  0, 1, 0, 0,  0, 0, 1, 0,  0, 0, 0, 1];
    }

    public sealed class TmaSection
    {
        public uint OriginalFrameCount { get; set; }
        public TmaControllerEntry[] Controllers { get; set; } = [];
    }

    /// <summary>
    /// Animation controller round-tripped via extras so TMA -> GLB -> TMA preserves visibility
    /// and footprint controllers without external fbximport input. Mirrors the binary fields
    /// of TmaVisibilityController (Type=1) and TmaFootprintController (Type=2).
    /// </summary>
    public sealed class TmaControllerEntry
    {
        public int Type { get; set; }
        public float Start { get; set; }
        public float End { get; set; }
        public float EaseIn { get; set; }
        public float EaseOut { get; set; }
        public bool InvertLogic { get; set; }
        public string AttachPointName { get; set; } = "";
        // Footprint-specific (Type=2)
        public float SpawnTime { get; set; }
        public string FootprintName { get; set; } = "";
        public int FootprintId { get; set; }
        public bool InvertTextureY { get; set; }
        public bool IsRightSide { get; set; }
    }

    public sealed class DdtEntry
    {
        public required string Material { get; init; }
        public DDTVersion Version { get; set; }
        public DDTUsage Usage { get; set; }
        public DDTAlpha Alpha { get; set; }
        public DDTFormat Format { get; set; }
        public byte MipLevels { get; set; }
        public ushort BaseWidth { get; set; }
        public ushort BaseHeight { get; set; }
        public byte[]? ColorTable { get; set; }
    }

    public sealed class AttachmentEntry
    {
        public required string Name { get; init; }
        public uint TypeFlag { get; set; }
        public float[] LocalMatrix { get; set; } = new float[12];
        public uint DummyBoneMode { get; set; }
        public uint DummyBoneTransformMode { get; set; }
        public string ForcedDummyBoneName { get; set; } = "";
        public int FrameLimit { get; set; } = -1;
        public float FramePosition { get; set; }
        public uint DummyBoneAnimationFilter { get; set; }
        public string[] SpecificAnimations { get; set; } = [];
    }

    public sealed class ModifiedBoneEntry
    {
        public int BoneIndex { get; set; }
        public float OriginalRadius { get; set; }
        public float RadiusMultiplier { get; set; }
    }

    public sealed class AutoAttachInfo
    {
        public bool AutoAttachCorpseToBone { get; set; }
        public string CorpseAttachBoneName { get; set; } = "";
        public string DefaultDeathAnimation { get; set; } = "";
        public bool UsesAutoGeneratedImpactPoints { get; set; }
        public string DefaultIdleAnimationPath { get; set; } = "";
    }

    /// <summary>
    /// Emits a mesh-node redundancy block: <c>extras.crybar.main_matrix</c>. Asset-level
    /// extras may be stripped by Blender; the mesh node retains the model scaling.
    /// </summary>
    public static void WriteMeshNodeRedundancy(Utf8JsonWriter w, IReadOnlyList<float> mainMatrix)
    {
        w.WriteStartObject("extras");
        w.WriteStartObject("crybar");
        w.WriteStartArray("main_matrix");
        foreach (var v in mainMatrix) w.WriteNumberValue(v);
        w.WriteEndArray();
        w.WriteEndObject();
        w.WriteEndObject();
    }

    /// <summary>
    /// Emits a glTF node marker so a future GLB reader can identify TMM attachment nodes.
    /// Unconditional (does not depend on caller-supplied extras).
    /// </summary>
    public static void WriteAttachmentMarker(Utf8JsonWriter w, int index)
    {
        w.WriteStartObject("extras");
        w.WriteStartObject("crybar");
        w.WriteString("node_type", "attachment");
        w.WriteNumber("index", index);
        w.WriteEndObject();
        w.WriteEndObject();
    }

    /// <summary>
    /// Writes this object as the value of a <c>"crybar"</c> property on the
    /// currently-open JSON object. The caller is expected to have written
    /// <c>extras: {</c> already (i.e. we're inside the extras object).
    /// </summary>
    public void Write(Utf8JsonWriter w)
    {
        w.WriteStartObject("crybar");

        w.WriteStartObject("tmm");
        WriteFloatArray(w, "extended_bbox", Tmm.ExtendedBbox);
        WriteFloatArray(w, "main_matrix", Tmm.MainMatrix);
        WriteStringArray(w, "submodels", Tmm.Submodels);
        w.WriteNumber("autoburn_mode", Tmm.AutoBurnMode);
        w.WriteBoolean("raytracing", Tmm.Raytracing);
        w.WriteBoolean("terrain_emb", Tmm.TerrainEmb);

        w.WriteStartArray("modified_bones");
        foreach (var mb in Tmm.ModifiedBones)
        {
            w.WriteStartObject();
            w.WriteNumber("bone_index", mb.BoneIndex);
            w.WriteNumber("original_radius", mb.OriginalRadius);
            w.WriteNumber("radius_multiplier", mb.RadiusMultiplier);
            w.WriteEndObject();
        }
        w.WriteEndArray();

        WriteFloatArray(w, "bone_collisions", Tmm.BoneCollisions);

        if (Tmm.AutoAttach is { } aa)
        {
            w.WriteStartObject("auto_attach");
            w.WriteBoolean("auto_attach_corpse_to_bone", aa.AutoAttachCorpseToBone);
            w.WriteString("corpse_attach_bone_name", aa.CorpseAttachBoneName);
            w.WriteString("default_death_animation", aa.DefaultDeathAnimation);
            w.WriteBoolean("uses_auto_generated_impact_points", aa.UsesAutoGeneratedImpactPoints);
            w.WriteString("default_idle_animation_path", aa.DefaultIdleAnimationPath);
            w.WriteEndObject();
        }

        w.WriteStartArray("impact_points");
        foreach (var p in Tmm.ImpactPoints)
        {
            w.WriteStartArray();
            foreach (var v in p) w.WriteNumberValue(v);
            w.WriteEndArray();
        }
        w.WriteEndArray();

        w.WriteStartArray("attachments");
        foreach (var a in Tmm.Attachments)
        {
            w.WriteStartObject();
            w.WriteString("name", a.Name);
            w.WriteNumber("type_flag", a.TypeFlag);
            WriteFloatArray(w, "local_matrix", a.LocalMatrix);
            w.WriteNumber("dummy_bone_mode", a.DummyBoneMode);
            w.WriteNumber("dummy_bone_transform_mode", a.DummyBoneTransformMode);
            w.WriteString("forced_dummy_bone_name", a.ForcedDummyBoneName);
            w.WriteNumber("frame_limit", a.FrameLimit);
            w.WriteNumber("frame_position", a.FramePosition);
            w.WriteNumber("dummy_bone_animation_filter", a.DummyBoneAnimationFilter);
            WriteStringArray(w, "specific_animations", a.SpecificAnimations);
            w.WriteEndObject();
        }
        w.WriteEndArray();

        WriteStringArray(w, "lossy_sections", Tmm.LossySections);
        w.WriteEndObject(); // tmm

        w.WriteStartObject("tma");
        foreach (var (name, entry) in Tma)
        {
            w.WriteStartObject(name);
            w.WriteNumber("original_frame_count", entry.OriginalFrameCount);
            w.WriteStartArray("controllers");
            foreach (var c in entry.Controllers)
            {
                w.WriteStartObject();
                w.WriteNumber("type", c.Type);
                if (c.Type == TmaControllerType.Visibility)
                {
                    w.WriteNumber("start", c.Start);
                    w.WriteNumber("end", c.End);
                    w.WriteNumber("ease_in", c.EaseIn);
                    w.WriteNumber("ease_out", c.EaseOut);
                    w.WriteBoolean("invert_logic", c.InvertLogic);
                    w.WriteString("attach_point", c.AttachPointName);
                }
                else if (c.Type == TmaControllerType.Footprint)
                {
                    w.WriteNumber("spawn_time", c.SpawnTime);
                    w.WriteString("footprint_name", c.FootprintName);
                    w.WriteNumber("footprint_id", c.FootprintId);
                    w.WriteBoolean("invert_texture_y", c.InvertTextureY);
                    w.WriteString("attach_point", c.AttachPointName);
                    w.WriteBoolean("is_right_side", c.IsRightSide);
                }
                w.WriteEndObject();
            }
            w.WriteEndArray();
            w.WriteEndObject();
        }
        w.WriteEndObject(); // tma

        w.WriteStartArray("ddt");
        foreach (var d in Ddt)
        {
            w.WriteStartObject();
            w.WriteString("material", d.Material);
            w.WriteString("version", d.Version.ToString());
            w.WriteString("usage", d.Usage.ToString());
            w.WriteString("alpha", d.Alpha.ToString());
            w.WriteString("format", d.Format.ToString());
            w.WriteNumber("mip_levels", d.MipLevels);
            w.WriteNumber("base_width", d.BaseWidth);
            w.WriteNumber("base_height", d.BaseHeight);
            if (d.ColorTable is { Length: > 0 })
                w.WriteBase64String("color_table", d.ColorTable);
            else
                w.WriteNull("color_table");
            w.WriteEndObject();
        }
        w.WriteEndArray(); // ddt

        w.WriteEndObject(); // crybar
    }

    static void WriteFloatArray(Utf8JsonWriter w, string name, IReadOnlyList<float> values)
    {
        w.WriteStartArray(name);
        foreach (var v in values) w.WriteNumberValue(v);
        w.WriteEndArray();
    }

    static void WriteStringArray(Utf8JsonWriter w, string name, IReadOnlyList<string> values)
    {
        w.WriteStartArray(name);
        foreach (var v in values) w.WriteStringValue(v);
        w.WriteEndArray();
    }

    /// <summary>
    /// Reads a <c>crybar</c> object from inside a glTF <c>extras</c> JSON element.
    /// Returns null if <c>extras</c> is null/missing or has no <c>crybar</c> key.
    /// </summary>
    public static GlbExtras? Read(JsonElement extras)
    {
        if (extras.ValueKind != JsonValueKind.Object) return null;
        if (!extras.TryGetProperty("crybar", out var crybar)) return null;
        if (crybar.ValueKind != JsonValueKind.Object) return null;

        var result = new GlbExtras();

        if (crybar.TryGetProperty("tmm", out var tmmEl) && tmmEl.ValueKind == JsonValueKind.Object)
        {
            ReadTmm(tmmEl, result.Tmm);
        }

        if (crybar.TryGetProperty("tma", out var tmaEl) && tmaEl.ValueKind == JsonValueKind.Object)
        {
            foreach (var prop in tmaEl.EnumerateObject())
            {
                var entry = new TmaSection();
                if (prop.Value.TryGetProperty("original_frame_count", out var fc))
                    entry.OriginalFrameCount = fc.GetUInt32();
                if (prop.Value.TryGetProperty("controllers", out var ctrls)
                    && ctrls.ValueKind == JsonValueKind.Array)
                {
                    var list = new List<TmaControllerEntry>();
                    foreach (var c in ctrls.EnumerateArray())
                    {
                        var ce = new TmaControllerEntry();
                        if (c.TryGetProperty("type", out var t)) ce.Type = t.GetInt32();
                        if (c.TryGetProperty("start", out var st)) ce.Start = st.GetSingle();
                        if (c.TryGetProperty("end", out var en)) ce.End = en.GetSingle();
                        if (c.TryGetProperty("ease_in", out var ei)) ce.EaseIn = ei.GetSingle();
                        if (c.TryGetProperty("ease_out", out var eo)) ce.EaseOut = eo.GetSingle();
                        if (c.TryGetProperty("invert_logic", out var il)) ce.InvertLogic = il.GetBoolean();
                        if (c.TryGetProperty("attach_point", out var ap)) ce.AttachPointName = ap.GetString() ?? "";
                        if (c.TryGetProperty("spawn_time", out var sp)) ce.SpawnTime = sp.GetSingle();
                        if (c.TryGetProperty("footprint_name", out var fn)) ce.FootprintName = fn.GetString() ?? "";
                        if (c.TryGetProperty("footprint_id", out var fid)) ce.FootprintId = fid.GetInt32();
                        if (c.TryGetProperty("invert_texture_y", out var ity)) ce.InvertTextureY = ity.GetBoolean();
                        if (c.TryGetProperty("is_right_side", out var rs)) ce.IsRightSide = rs.GetBoolean();
                        list.Add(ce);
                    }
                    entry.Controllers = list.ToArray();
                }
                result.Tma[prop.Name] = entry;
            }
        }

        if (crybar.TryGetProperty("ddt", out var ddtEl) && ddtEl.ValueKind == JsonValueKind.Array)
        {
            foreach (var d in ddtEl.EnumerateArray())
            {
                var entry = new DdtEntry { Material = d.GetProperty("material").GetString() ?? "" };
                if (d.TryGetProperty("version", out var ver) && Enum.TryParse<DDTVersion>(ver.GetString(), out var v)) entry.Version = v;
                if (d.TryGetProperty("usage", out var us) && Enum.TryParse<DDTUsage>(us.GetString(), out var u)) entry.Usage = u;
                if (d.TryGetProperty("alpha", out var al) && Enum.TryParse<DDTAlpha>(al.GetString(), out var a)) entry.Alpha = a;
                if (d.TryGetProperty("format", out var fm) && Enum.TryParse<DDTFormat>(fm.GetString(), out var f)) entry.Format = f;
                if (d.TryGetProperty("mip_levels", out var ml)) entry.MipLevels = ml.GetByte();
                if (d.TryGetProperty("base_width", out var bw)) entry.BaseWidth = (ushort)bw.GetUInt32();
                if (d.TryGetProperty("base_height", out var bh)) entry.BaseHeight = (ushort)bh.GetUInt32();
                if (d.TryGetProperty("color_table", out var ct) && ct.ValueKind == JsonValueKind.String)
                    entry.ColorTable = ct.GetBytesFromBase64();
                result.Ddt.Add(entry);
            }
        }

        return result;
    }

    /// <summary>
    /// Builds a <see cref="GlbExtras"/> from the source TMM/TMA/DDT files at GLB export time.
    /// Material name to DDT mapping uses the order in <paramref name="ddts"/>;
    /// caller is responsible for the alignment.
    /// </summary>
    public static GlbExtras From(TmmFile tmm,
        IReadOnlyList<(string Name, TmaFile Tma)> tmas,
        IReadOnlyList<(string Material, DDTImage Ddt)> ddts)
    {
        var extras = new GlbExtras();

        if (tmm.Parsed)
        {
            extras.Tmm.ExtendedBbox =
            [
                tmm.ExtendedBoundingBox.MinX, tmm.ExtendedBoundingBox.MinY, tmm.ExtendedBoundingBox.MinZ,
                tmm.ExtendedBoundingBox.MaxX, tmm.ExtendedBoundingBox.MaxY, tmm.ExtendedBoundingBox.MaxZ,
            ];
            extras.Tmm.MainMatrix = (float[])tmm.MainMatrix!.Clone();
            extras.Tmm.Submodels = (string[])tmm.Submodels!.Clone();
            extras.Tmm.AutoBurnMode = tmm.AutoBurnMode;
            extras.Tmm.Raytracing = tmm.EnableRayTracingForModel;
            extras.Tmm.TerrainEmb = tmm.IsTerrainEmbellishment;

            if (tmm.ModifiedBones is { Length: > 0 })
            {
                extras.Tmm.ModifiedBones = tmm.ModifiedBones.Select(mb => new ModifiedBoneEntry
                {
                    BoneIndex = mb.BoneIndex,
                    OriginalRadius = mb.OriginalRadius,
                    RadiusMultiplier = mb.RadiusMultiplier,
                }).ToArray();
            }

            if (tmm.Bones is { Length: > 0 })
            {
                var collisions = new float[tmm.Bones.Length * 4];
                for (int i = 0; i < tmm.Bones.Length; i++)
                {
                    var b = tmm.Bones[i];
                    collisions[i * 4]     = b.CollisionOffsetX;
                    collisions[i * 4 + 1] = b.CollisionOffsetY;
                    collisions[i * 4 + 2] = b.CollisionOffsetZ;
                    collisions[i * 4 + 3] = b.Radius;
                }
                extras.Tmm.BoneCollisions = collisions;
            }

            if (tmm.AutoAttachInfo is { } aa)
            {
                extras.Tmm.AutoAttach = new AutoAttachInfo
                {
                    AutoAttachCorpseToBone = aa.AutoAttachCorpseToBone,
                    CorpseAttachBoneName = aa.CorpseAttachBoneName,
                    DefaultDeathAnimation = aa.DefaultDeathAnimation,
                    UsesAutoGeneratedImpactPoints = aa.UsesAutoGeneratedImpactPoints,
                    DefaultIdleAnimationPath = aa.DefaultIdleAnimationPath,
                };
                if (aa.ManualImpactPoints is { Length: > 0 })
                    extras.Tmm.ImpactPoints = aa.ManualImpactPoints
                        .Select(p => (float[])p.Clone()).ToArray();
            }

            if (tmm.Attachments is { Length: > 0 })
            {
                extras.Tmm.Attachments = tmm.Attachments.Select(a => new AttachmentEntry
                {
                    Name = a.Name,
                    TypeFlag = a.TypeFlag,
                    LocalMatrix = (float[])a.LocalTransformMatrix.Clone(),
                    DummyBoneMode = a.DummyBoneMode,
                    DummyBoneTransformMode = a.DummyBoneTransformMode,
                    ForcedDummyBoneName = a.ForcedDummyBoneName,
                    FrameLimit = a.FrameLimit,
                    FramePosition = a.FramePosition,
                    DummyBoneAnimationFilter = a.DummyBoneAnimationFilter,
                    SpecificAnimations = (string[])a.DummySpecificAnimations.Clone(),
                }).ToArray();
            }

            if (tmm.Destruction != null) extras.Tmm.LossySections.Add("destruction");
            if (tmm.PhysicsTemplate != null) extras.Tmm.LossySections.Add("physics");
            if (tmm.TreeDestructionBones is { Length: > 0 }) extras.Tmm.LossySections.Add("tree_destruction");
            if (tmm.ClickVolume?.AreVoxelsDefined == true) extras.Tmm.LossySections.Add("voxels");
        }

        foreach (var (name, tma) in tmas)
        {
            if (!tma.Parsed) continue;
            var section = new TmaSection
            {
                OriginalFrameCount = tma.FrameCount,
            };
            if (tma.Controllers is { Length: > 0 })
            {
                var list = new List<TmaControllerEntry>(tma.Controllers.Length);
                foreach (var c in tma.Controllers)
                {
                    switch (c)
                    {
                        case TmaVisibilityController v:
                            list.Add(new TmaControllerEntry
                            {
                                Type = TmaControllerType.Visibility,
                                Start = v.Start,
                                End = v.End,
                                EaseIn = v.EaseIn,
                                EaseOut = v.EaseOut,
                                InvertLogic = v.InvertLogic,
                                AttachPointName = v.AttachPointName,
                            });
                            break;
                        case TmaFootprintController f:
                            list.Add(new TmaControllerEntry
                            {
                                Type = TmaControllerType.Footprint,
                                SpawnTime = f.SpawnTime,
                                FootprintName = f.FootprintName,
                                FootprintId = f.FootprintId,
                                InvertTextureY = f.InvertTextureY,
                                AttachPointName = f.AttachPointName,
                                IsRightSide = f.IsRightSide,
                            });
                            break;
                    }
                }
                section.Controllers = list.ToArray();
            }
            extras.Tma[name] = section;
        }

        foreach (var (material, ddt) in ddts)
        {
            if (!ddt.HeaderParsed) continue;
            extras.Ddt.Add(new DdtEntry
            {
                Material = material,
                Version = ddt.Version,
                Usage = ddt.UsageFlag,
                Alpha = ddt.AlphaFlag,
                Format = ddt.FormatFlag,
                MipLevels = ddt.MipmapLevels,
                BaseWidth = ddt.BaseWidth,
                BaseHeight = ddt.BaseHeight,
                ColorTable = ddt.ColorTable?.ToArray(),
            });
        }

        return extras;
    }

    static void ReadTmm(JsonElement el, TmmSection tmm)
    {
        if (el.TryGetProperty("extended_bbox", out var bb)) tmm.ExtendedBbox = ReadFloatArray(bb);
        if (el.TryGetProperty("main_matrix", out var mm)) tmm.MainMatrix = ReadFloatArray(mm);
        if (el.TryGetProperty("submodels", out var sm)) tmm.Submodels = ReadStringArray(sm);
        if (el.TryGetProperty("autoburn_mode", out var ab)) tmm.AutoBurnMode = ab.GetByte();
        if (el.TryGetProperty("raytracing", out var rt)) tmm.Raytracing = rt.GetBoolean();
        if (el.TryGetProperty("terrain_emb", out var te)) tmm.TerrainEmb = te.GetBoolean();

        if (el.TryGetProperty("bone_collisions", out var bc)) tmm.BoneCollisions = ReadFloatArray(bc);

        if (el.TryGetProperty("modified_bones", out var mb) && mb.ValueKind == JsonValueKind.Array)
        {
            var list = new List<ModifiedBoneEntry>();
            foreach (var item in mb.EnumerateArray())
            {
                list.Add(new ModifiedBoneEntry
                {
                    BoneIndex = item.GetProperty("bone_index").GetInt32(),
                    OriginalRadius = item.GetProperty("original_radius").GetSingle(),
                    RadiusMultiplier = item.GetProperty("radius_multiplier").GetSingle(),
                });
            }
            tmm.ModifiedBones = list.ToArray();
        }

        if (el.TryGetProperty("auto_attach", out var aa) && aa.ValueKind == JsonValueKind.Object)
        {
            tmm.AutoAttach = new AutoAttachInfo
            {
                AutoAttachCorpseToBone = aa.GetProperty("auto_attach_corpse_to_bone").GetBoolean(),
                CorpseAttachBoneName = aa.GetProperty("corpse_attach_bone_name").GetString() ?? "",
                DefaultDeathAnimation = aa.GetProperty("default_death_animation").GetString() ?? "",
                UsesAutoGeneratedImpactPoints = aa.GetProperty("uses_auto_generated_impact_points").GetBoolean(),
                DefaultIdleAnimationPath = aa.GetProperty("default_idle_animation_path").GetString() ?? "",
            };
        }

        if (el.TryGetProperty("impact_points", out var ip) && ip.ValueKind == JsonValueKind.Array)
        {
            var list = new List<float[]>();
            foreach (var p in ip.EnumerateArray()) list.Add(ReadFloatArray(p));
            tmm.ImpactPoints = list.ToArray();
        }

        if (el.TryGetProperty("attachments", out var atts) && atts.ValueKind == JsonValueKind.Array)
        {
            var list = new List<AttachmentEntry>();
            foreach (var a in atts.EnumerateArray())
            {
                var entry = new AttachmentEntry { Name = a.GetProperty("name").GetString() ?? "" };
                if (a.TryGetProperty("type_flag", out var tf)) entry.TypeFlag = tf.GetUInt32();
                if (a.TryGetProperty("local_matrix", out var lm)) entry.LocalMatrix = ReadFloatArray(lm);
                if (a.TryGetProperty("dummy_bone_mode", out var dbm)) entry.DummyBoneMode = dbm.GetUInt32();
                if (a.TryGetProperty("dummy_bone_transform_mode", out var dbt)) entry.DummyBoneTransformMode = dbt.GetUInt32();
                if (a.TryGetProperty("forced_dummy_bone_name", out var fdb)) entry.ForcedDummyBoneName = fdb.GetString() ?? "";
                if (a.TryGetProperty("frame_limit", out var fl)) entry.FrameLimit = fl.GetInt32();
                if (a.TryGetProperty("frame_position", out var fp)) entry.FramePosition = fp.GetSingle();
                if (a.TryGetProperty("dummy_bone_animation_filter", out var daf)) entry.DummyBoneAnimationFilter = daf.GetUInt32();
                if (a.TryGetProperty("specific_animations", out var sa)) entry.SpecificAnimations = ReadStringArray(sa);
                list.Add(entry);
            }
            tmm.Attachments = list.ToArray();
        }

        if (el.TryGetProperty("lossy_sections", out var ls) && ls.ValueKind == JsonValueKind.Array)
        {
            tmm.LossySections.Clear();
            foreach (var s in ls.EnumerateArray()) tmm.LossySections.Add(s.GetString() ?? "");
        }
    }

    static float[] ReadFloatArray(JsonElement el)
    {
        var list = new List<float>();
        foreach (var v in el.EnumerateArray()) list.Add(v.GetSingle());
        return list.ToArray();
    }

    static string[] ReadStringArray(JsonElement el)
    {
        var list = new List<string>();
        foreach (var v in el.EnumerateArray()) list.Add(v.GetString() ?? "");
        return list.ToArray();
    }
}
