using System.Text;
using System.Xml;

namespace CryBar.Export;

public class MaterialInfo
{
    public string Name { get; init; } = "";
    public Dictionary<string, string> Textures { get; init; } = new(); // e.g. "BaseColor" -> "atlantean\...\armory_basecolor"
}

/// <summary>
/// Parses AoM:Retold .material XML files and generates Wavefront .mtl output.
/// </summary>
public static class MaterialExporter
{
    /// <summary>
    /// Parses material XML content, extracting submaterial definitions and their texture references.
    /// </summary>
    public static List<MaterialInfo> ParseMaterialXml(string xml)
    {
        var result = new List<MaterialInfo>();
        using var reader = XmlReader.Create(new StringReader(xml));

        MaterialInfo? currentMat = null;

        while (reader.Read())
        {
            if (reader.NodeType == XmlNodeType.Element)
            {
                if (reader.Name == "submaterial")
                {
                    currentMat = new MaterialInfo
                    {
                        Name = reader.GetAttribute("name") ?? "",
                        Textures = new Dictionary<string, string>()
                    };
                }
                else if (reader.Name == "texture" && currentMat != null)
                {
                    var texName = reader.GetAttribute("name") ?? "";
                    var texOverride = reader.GetAttribute("override") ?? "";
                    if (!string.IsNullOrEmpty(texName) && !string.IsNullOrEmpty(texOverride))
                    {
                        currentMat.Textures[texName] = texOverride;
                    }
                }
            }
            else if (reader.NodeType == XmlNodeType.EndElement && reader.Name == "submaterial")
            {
                if (currentMat != null && currentMat.Textures.Count > 0)
                    result.Add(currentMat);
                currentMat = null;
            }
        }

        return result;
    }

    /// <summary>
    /// Generates a Wavefront .mtl file from parsed materials and resolved texture filenames.
    /// </summary>
    /// <param name="materials">Parsed material definitions</param>
    /// <param name="resolvedTextures">Maps original texture path -> resolved local filename (e.g. "armory_basecolor.tga")</param>
    public static string GenerateMtl(List<MaterialInfo> materials, Dictionary<string, string> resolvedTextures)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by CryBarEditor");
        sb.AppendLine();

        foreach (var mat in materials)
        {
            sb.AppendLine($"newmtl {mat.Name}");
            sb.AppendLine("Ka 0.2 0.2 0.2");
            sb.AppendLine("Kd 0.8 0.8 0.8");
            sb.AppendLine("Ks 0.0 0.0 0.0");
            sb.AppendLine("d 1.0");

            foreach (var (texName, texPath) in mat.Textures)
            {
                var resolved = resolvedTextures.GetValueOrDefault(texPath);
                if (resolved == null) continue;

                if (IsBaseColorRole(texName))
                {
                    sb.AppendLine($"map_Kd {resolved}");
                }
                else if (IsNormalRole(texName))
                {
                    sb.AppendLine($"norm {resolved}");
                    sb.AppendLine($"map_Bump {resolved}");
                }
                else
                {
                    sb.AppendLine($"# {texName}: {resolved}");
                }
            }

            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>
    /// Returns all unique texture paths referenced across the given materials.
    /// </summary>
    public static List<string> GetAllTexturePaths(List<MaterialInfo> materials)
    {
        return materials
            .SelectMany(m => m.Textures.Values)
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    /// <summary>True if the texture role name maps to glTF's pbrMetallicRoughness.baseColorTexture.</summary>
    public static bool IsBaseColorRole(string textureName) =>
        textureName.Equals("BaseColor", StringComparison.OrdinalIgnoreCase) ||
        textureName.Equals("Diffuse",   StringComparison.OrdinalIgnoreCase);

    /// <summary>True if the texture role name maps to glTF's normalTexture.</summary>
    public static bool IsNormalRole(string textureName) =>
        textureName.Equals("Normals", StringComparison.OrdinalIgnoreCase) ||
        textureName.Equals("Normal",  StringComparison.OrdinalIgnoreCase);
}
