using System.Text.Json;
using CryBar;
using CryBar.Export;
using CryBar.TMM;

namespace CryBar.Tests;

public class GlbExtrasTests
{
    [Fact]
    public void GlbExtras_DefaultConstruction_HasEmptyFields()
    {
        var extras = new GlbExtras();
        Assert.NotNull(extras.Tmm);
        Assert.NotNull(extras.Tma);
        Assert.NotNull(extras.Ddt);
        Assert.Empty(extras.Tma);
        Assert.Empty(extras.Ddt);
    }

    [Fact]
    public void TmmExtras_DefaultMainMatrix_IsIdentity()
    {
        var tmm = new GlbExtras.TmmSection();
        Assert.Equal(16, tmm.MainMatrix.Length);
        Assert.Equal(1.0f, tmm.MainMatrix[0]);
        Assert.Equal(1.0f, tmm.MainMatrix[5]);
        Assert.Equal(1.0f, tmm.MainMatrix[10]);
        Assert.Equal(1.0f, tmm.MainMatrix[15]);
    }

    [Fact]
    public void AttachmentExtras_DefaultLocalMatrix_IsZeroLength()
    {
        var att = new GlbExtras.AttachmentEntry { Name = "test" };
        Assert.NotNull(att.LocalMatrix);
        Assert.Equal(12, att.LocalMatrix.Length);
        Assert.Empty(att.SpecificAnimations);
    }

    [Fact]
    public void Write_PopulatedExtras_EmitsExpectedStructure()
    {
        var extras = new GlbExtras
        {
            Tmm = new GlbExtras.TmmSection
            {
                ExtendedBbox = [-1, -1, -1, 1, 1, 1],
                MainMatrix = [0.5f, 0, 0, 0,  0, 0.5f, 0, 0,  0, 0, 0.5f, 0,  0, 0, 0, 1],
                Submodels = ["default", "alt"],
                AutoBurnMode = 2,
                Raytracing = true,
            },
            Tma =
            {
                ["idle"] = new GlbExtras.TmaSection { HadControllers = false, OriginalFrameCount = 30 }
            },
            Ddt =
            {
                new GlbExtras.DdtEntry
                {
                    Material = "body",
                    Version = DDTVersion.RTS4,
                    Format = DDTFormat.DXT5,
                    MipLevels = 9,
                    BaseWidth = 256,
                    BaseHeight = 256,
                }
            }
        };
        extras.Tmm.LossySections.Add("destruction");

        using var ms = new MemoryStream();
        using (var w = new Utf8JsonWriter(ms))
        {
            w.WriteStartObject();
            extras.Write(w);
            w.WriteEndObject();
        }

        var json = JsonDocument.Parse(ms.ToArray());
        var crybar = json.RootElement.GetProperty("crybar");

        Assert.Equal(0.5f, crybar.GetProperty("tmm").GetProperty("main_matrix")[0].GetSingle());
        Assert.Equal(2, crybar.GetProperty("tmm").GetProperty("autoburn_mode").GetByte());
        Assert.True(crybar.GetProperty("tmm").GetProperty("raytracing").GetBoolean());
        Assert.Equal("destruction", crybar.GetProperty("tmm").GetProperty("lossy_sections")[0].GetString());
        Assert.Equal(30u, crybar.GetProperty("tma").GetProperty("idle").GetProperty("original_frame_count").GetUInt32());
        Assert.Equal("body", crybar.GetProperty("ddt")[0].GetProperty("material").GetString());
        Assert.Equal("DXT5", crybar.GetProperty("ddt")[0].GetProperty("format").GetString());
    }

    [Fact]
    public void Write_OmitsBoundsRadiusBboxAndVersion()
    {
        var extras = new GlbExtras();
        using var ms = new MemoryStream();
        using (var w = new Utf8JsonWriter(ms))
        {
            w.WriteStartObject();
            extras.Write(w);
            w.WriteEndObject();
        }
        var jsonText = System.Text.Encoding.UTF8.GetString(ms.ToArray());
        Assert.DoesNotContain("\"bbox\"", jsonText);
        Assert.DoesNotContain("\"bounds_radius\"", jsonText);
        Assert.DoesNotContain("\"version\"", jsonText);
        Assert.DoesNotContain("\"duration\"", jsonText);
        Assert.DoesNotContain("\"controller_count\"", jsonText);
    }

    [Fact]
    public void ReadWrite_RoundTrip_PreservesAllFields()
    {
        var original = new GlbExtras
        {
            Tmm = new GlbExtras.TmmSection
            {
                ExtendedBbox = [-2, -3, -4, 5, 6, 7],
                MainMatrix = [0.0115f, 0, 0, 0,  0, 0.0115f, 0, 0,  0, 0, 0.0115f, 0,  0, 0, 0, 1],
                Submodels = ["default", "broken"],
                AutoBurnMode = 1,
                Raytracing = true,
                TerrainEmb = false,
                ModifiedBones =
                [
                    new GlbExtras.ModifiedBoneEntry { BoneIndex = 3, OriginalRadius = 0.1f, RadiusMultiplier = 2.0f }
                ],
                AutoAttach = new GlbExtras.AutoAttachInfo
                {
                    AutoAttachCorpseToBone = true,
                    CorpseAttachBoneName = "spine",
                    DefaultDeathAnimation = "die",
                    UsesAutoGeneratedImpactPoints = false,
                    DefaultIdleAnimationPath = "anims/idle.tma",
                },
                ImpactPoints = [[0.1f, 0.2f, 0.3f, 1.0f]],
                Attachments =
                [
                    new GlbExtras.AttachmentEntry
                    {
                        Name = "spear_tip",
                        TypeFlag = 0,
                        LocalMatrix = [1,0,0,0, 0,1,0,0, 0,0,1,0],
                        ForcedDummyBoneName = "tip",
                        FrameLimit = -1,
                        SpecificAnimations = ["a", "b"]
                    }
                ],
            },
            Tma =
            {
                ["walk"] = new GlbExtras.TmaSection { HadControllers = true, OriginalFrameCount = 24 }
            },
            Ddt =
            {
                new GlbExtras.DdtEntry
                {
                    Material = "body",
                    Version = DDTVersion.RTS4,
                    Usage = DDTUsage.Bump,
                    Alpha = DDTAlpha.None,
                    Format = DDTFormat.DXT5,
                    MipLevels = 9, BaseWidth = 256, BaseHeight = 256,
                    ColorTable = [1, 2, 3, 4]
                }
            }
        };
        original.Tmm.LossySections.Add("destruction");
        original.Tmm.LossySections.Add("physics");

        using var ms = new MemoryStream();
        using (var w = new Utf8JsonWriter(ms))
        {
            w.WriteStartObject();
            original.Write(w);
            w.WriteEndObject();
        }
        var doc = JsonDocument.Parse(ms.ToArray());
        var roundTripped = GlbExtras.Read(doc.RootElement);
        Assert.NotNull(roundTripped);

        Assert.Equal(original.Tmm.ExtendedBbox, roundTripped.Tmm.ExtendedBbox);
        Assert.Equal(original.Tmm.MainMatrix, roundTripped.Tmm.MainMatrix);
        Assert.Equal(original.Tmm.Submodels, roundTripped.Tmm.Submodels);
        Assert.Equal(original.Tmm.AutoBurnMode, roundTripped.Tmm.AutoBurnMode);
        Assert.Equal(original.Tmm.Raytracing, roundTripped.Tmm.Raytracing);

        Assert.Single(roundTripped.Tmm.ModifiedBones);
        Assert.Equal(3, roundTripped.Tmm.ModifiedBones[0].BoneIndex);

        Assert.NotNull(roundTripped.Tmm.AutoAttach);
        Assert.Equal("spine", roundTripped.Tmm.AutoAttach!.CorpseAttachBoneName);

        Assert.Single(roundTripped.Tmm.ImpactPoints);
        Assert.Equal(0.1f, roundTripped.Tmm.ImpactPoints[0][0]);

        Assert.Single(roundTripped.Tmm.Attachments);
        Assert.Equal("spear_tip", roundTripped.Tmm.Attachments[0].Name);
        Assert.Equal(2, roundTripped.Tmm.Attachments[0].SpecificAnimations.Length);

        Assert.Equal(2, roundTripped.Tmm.LossySections.Count);

        Assert.True(roundTripped.Tma["walk"].HadControllers);
        Assert.Equal(24u, roundTripped.Tma["walk"].OriginalFrameCount);

        Assert.Single(roundTripped.Ddt);
        Assert.Equal(DDTFormat.DXT5, roundTripped.Ddt[0].Format);
        Assert.Equal(new byte[] { 1, 2, 3, 4 }, roundTripped.Ddt[0].ColorTable);
    }

    [Fact]
    public void Read_NoExtrasObject_ReturnsNull()
    {
        var doc = JsonDocument.Parse("{ \"foo\": 1 }");
        Assert.Null(GlbExtras.Read(doc.RootElement));
    }

    [Fact]
    public void Read_NoCrybarKey_ReturnsNull()
    {
        var doc = JsonDocument.Parse("{ \"otherTool\": { } }");
        Assert.Null(GlbExtras.Read(doc.RootElement));
    }

    [Fact]
    public void From_StampsTmmFieldsCorrectly()
    {
        var tmmBytes = TmmTestHelpers.CreateSyntheticTmm(
            version: 37,
            materials: ["body"],
            numBones: 0,
            numAttachments: 0);
        var tmm = new TmmFile(tmmBytes);
        Assert.True(tmm.Parsed);

        var extras = GlbExtras.From(tmm, [], []);

        Assert.Equal(tmm.MainMatrix!, extras.Tmm.MainMatrix);
        Assert.Equal(tmm.AutoBurnMode, extras.Tmm.AutoBurnMode);
        Assert.Equal(tmm.IsTerrainEmbellishment, extras.Tmm.TerrainEmb);
        Assert.Equal(tmm.EnableRayTracingForModel, extras.Tmm.Raytracing);
        Assert.Equal(tmm.Submodels!, extras.Tmm.Submodels);
    }

    [Fact]
    public void From_NoModifiedBonesNoAutoAttach_LeavesEmptyDefaults()
    {
        var tmmBytes = TmmTestHelpers.CreateSyntheticTmm();
        var tmm = new TmmFile(tmmBytes);

        var extras = GlbExtras.From(tmm, [], []);

        Assert.Empty(extras.Tmm.ModifiedBones);
        Assert.Null(extras.Tmm.AutoAttach);
        Assert.Empty(extras.Tmm.ImpactPoints);
        Assert.Empty(extras.Tmm.Attachments);
    }

    [Fact]
    public void From_NamedTmas_KeysExtrasByGivenName()
    {
        var tmmBytes = TmmTestHelpers.CreateSyntheticTmm();
        var tmm = new TmmFile(tmmBytes);

        var tma1Bytes = TmmTestHelpers.CreateSyntheticTma(numBones: 0, frameCount: 30, duration: 1.0f);
        var tma2Bytes = TmmTestHelpers.CreateSyntheticTma(numBones: 0, frameCount: 24, duration: 0.8f);
        var tma1 = new TmaFile(tma1Bytes);
        var tma2 = new TmaFile(tma2Bytes);

        var named = new (string, TmaFile)[] { ("idle", tma1), ("walk", tma2) };
        var extras = GlbExtras.From(tmm, named, []);

        Assert.True(extras.Tma.ContainsKey("idle"));
        Assert.True(extras.Tma.ContainsKey("walk"));
        Assert.Equal(30u, extras.Tma["idle"].OriginalFrameCount);
        Assert.Equal(24u, extras.Tma["walk"].OriginalFrameCount);
    }
}
